In [ ]:
from tkinter import *
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
# import filedialog module
from tkinter import filedialog
import tkinter as tk
from matplotlib.figure import Figure
from pandas import DataFrame
from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg, 
NavigationToolbar2Tk)

# Function for opening the
# file explorer window
def browseFiles():
    filename = filedialog.askopenfilename(initialdir = "/",
                                          title = "Select a File",
                                          filetypes = (("Text files",
                                                        "*.txt*"),
                                                       ("all files",
                                                        "*.*")))
      
    # Change label contents
    file_name.configure(text=""+filename)
      
def Process1():
    dataset1 = file_name.cget("text")
    dataset = pd.read_csv(dataset1)
    X = dataset.iloc[:,0:5].values
    y = dataset.iloc[:,36].values
    from sklearn.preprocessing import LabelEncoder
    labelencoder_X = LabelEncoder()
    X[:,0]= labelencoder_X.fit_transform(X[:,0])
    print("\n",X,"\n")
    T.insert(tk.END, X)
        
def Process2():
    T.delete("1.0", "end")
    dataset1 = file_name.cget("text")
    dataset = pd.read_csv(dataset1)
    X = dataset.iloc[:,0:5].values
    y = dataset.iloc[:,36].values
    from sklearn.preprocessing import LabelEncoder
    labelencoder_X = LabelEncoder()
    X[:,0]= labelencoder_X.fit_transform(X[:,0])
    X = np.array(X)
    y = np.array(y)
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.20,random_state = 33)
    neigh = KNeighborsRegressor(n_neighbors=5)
    neigh.fit(X_train,y_train)
    predicted1 = neigh.predict(X_test)
    #print(X_test)
    #print(y_test)
    print("Prediction Result: ",predicted1)
    T.insert(tk.END, predicted1)
    fig = Figure(figsize = (3, 3),
                 dpi = 100)
    plt = fig.add_subplot(111)
    plt.plot(y_test,label='Actual')
    plt.plot(predicted1,label='Predicted')
    canvas = FigureCanvasTkAgg(fig, master=window)
    canvas.draw()
    canvas.get_tk_widget().grid(row=9, column=1, ipadx=40, ipady=20)

def Process3():
    T.delete("1.0", "end")
    dataset1 = file_name.cget("text")
    dataset = pd.read_csv(dataset1)
    X = dataset.iloc[:,0:5].values
    y = dataset.iloc[:,36].values
    from sklearn.preprocessing import LabelEncoder
    labelencoder_X = LabelEncoder()
    X[:,0]= labelencoder_X.fit_transform(X[:,0])
    X = np.array(X)
    y = np.array(y)
    #X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.20,random_state = 33)
    for i in range(1,100):
        X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.20,random_state = i)
        regressor = DecisionTreeRegressor(max_depth=6)
        regressor.fit(X_train,y_train)
    predicted1 = regressor.predict(X_test)
    #print('i =',i)
    print("Prediction Result: ",predicted1)
    T.insert(tk.END, predicted1)
    fig = Figure(figsize = (3, 3),
                 dpi = 100)
    plt = fig.add_subplot(111)
    plt.plot(y_test,label='Actual')
    plt.plot(predicted1,label='Predicted')
    canvas = FigureCanvasTkAgg(fig, master=window)
    canvas.draw()
    canvas.get_tk_widget().grid(row=9, column=1, ipadx=40, ipady=20)
    
                                                                                                  
# Create the root window
window = tk.Tk()
  
# Set window title
window.title('File Explorer')
  
# Set window size
window.geometry("500x500")
  
#Set window background color
window.config(background = "white")
  
# Create a File Explorer label
label_file_explorer = Label(window,
                            text = "Rainfall Prediction using Machine Learning",
                            width = 100, height = 4,
                            fg = "blue")

file_name = Label(window, 
                  text = "No Uploads",
                            width = 100, height = 2,
                            fg = "blue")
   
button_explore = Button(window,
                        text = "Browse Files",
                        command = browseFiles, width = 15)

button_process1 = Button(window,
                        text = "Preprocessing",
                        command = Process1, width = 15)

button_process2 = Button(window,
                        text = "KNN Algorithm",
                        command = Process2, width = 15)

button_process3 = Button(window,
                        text = "Decision Tree",
                        command = Process3, width = 15)
  
button_exit = Button(window,
                     text = "Exit",
                     command=window.destroy, width = 15)

T = Text(window, height = 2, width = 52)
  
# Grid method is chosen for placing
# the widgets at respective positions
# in a table like structure by
# specifying rows and columns
label_file_explorer.grid(column = 1, row = 1)

file_name.grid(column = 1, row = 2)
  
button_explore.grid(column = 1, row = 3, pady = 4, padx = 100)

button_process1.grid(column = 1, row = 4, pady = 4, padx = 100)

button_process2.grid(column = 1, row = 5, pady = 4, padx = 100)

button_process3.grid(column = 1, row = 6, pady = 4, padx = 100)
  
button_exit.grid(column = 1,row = 7, pady = 4, padx = 100)

T.grid(column = 1,row = 8)
  
# Let the window wait for any events
window.mainloop()


 [[0 1995 1 24.9 10.7]
 [0 1995 2 27.7 15.0]
 [0 1995 3 33.0 19.5]
 ...
 [31 2012 10 31.6 24.3]
 [31 2012 11 30.6 18.3]
 [31 2012 12 27.7 16.4]] 

Prediction Result:  [329.86153846 752.75862069   3.91549296 ... 134.38297872 476.57761733
 374.34507042]
